.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Sébastien Ducoulombier <seb@ldd.fr>,
.\"
.TH Relaidecourriel 1 "April 22 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
relaidecourriel \- relai de courriel du gestionnaire d'affectations
.SH SYNOPSIS
Dans /etc/aliases :
.B prefixe: |/usr/sbin/relai_de_courriel
.SH DESCRIPTION
This manual page documents briefly the
.B relaidecourriel
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBrelaidecourriel\fP lit le message entrant sur son entrée standard. Il lit /etc/relaidecourriel.ini pour savoir comment se connecter à la base de données centrale.
.SH SEE ALSO
.BR aliases (5),
.BR newaliases (1),
.BR sendmail (1).
